### ISSUE TITLE
Add support for short circuit all/any

### ISSUE THREAD

**Issue by hucker** [avilum/linqit#11]
In looking at the code I can see that the  all/any methods traverse the whole list.  I have a tested  fix with short circuiting for these methods...but have never done pull requests...

**Comment by avilum** [comment]
This issue was resolved in PR #12;
Thank you.

**Comment by hucker** [comment]
Avi:
I just noticed that I missed doing something on the changes I made in Dec/Jan, and it looks like they are preventing me from showing up as a contributor on this project.  What have I missed?

**Comment by avilum** [comment]
Hey,

Maybe it shows me as the contributor for the files because I am the one
that clicked on “Merge”?
You can add a blank line or some small fix somewhere. Another option is to
revert them and merge them back, but you’ll merge this time and I will only
approve them.

That’s the least I can do, tell me what you think
